### ISSUE TITLE
proxy use

### ISSUE THREAD

**Issue by Joel-Costamagna** [ipinfo/cli#29]
I have a proxy set up on my machine, with a global http_proxy env variable so i can fetch ipinfo via curl

is there a way to make the ipinfo cli tool go through the proxy?

**Comment by UmanShahzad** [comment]
Hey @Joel-Costamagna ,

It should automatically work for `https_proxy`/`HTTPS_PROXY`, but I noticed it isn't working for the unsecure version. Will take a look.

**Comment by UmanShahzad** [comment]
Ah it's because the Go HTTP client library by default only uses the HTTPS proxy env var for `https://` endpoints. Since we always use `https://ipinfo.io/` as the base host, the HTTP-only version of the proxy env var is ignored. This is the same behavior as for curl based off of some local testing I just did.

I guess we can override that behavior if forced (i.e. forcefully make an unsecure connection with a proxy, which will then make a secure connection with `https://ipinfo.io`), but I just want to confirm if that's what you really want? Does your proxy support HTTPS connections, so that you can just set `https_proxy` or `HTTPS_PROXY` instead?

**Comment by Joel-Costamagna** [comment]
hello, it works fine by setting https proxy, thanks for your help
